name: amazon_nlp
channels: !!python/tuple
- !!python/unicode
  'defaults'
dependencies:
- python == 3.5
- _license=1.1=py35_1
- _nb_ext_conf=0.3.0=py35_0
- alabaster=0.7.10=py35_0
- amueller::wordcloud=1.2.1=py35_0
- anaconda-clean=1.1.0=py35_0
- anaconda-client=1.6.2=py35_0
- anaconda=custom=py35_0
- anaconda-navigator=1.5.2=py35_0
- anaconda-project=0.4.1=py35_0
- argcomplete=1.0.0=py35_1
- astroid=1.4.9=py35_0
- astropy=1.3.2=np112py35_0
- babel=2.4.0=py35_0
- backports=1.0=py35_0
- beautifulsoup4=4.5.3=py35_0
- bitarray=0.8.1=py35_0
- blaze=0.10.1=py35_0
- bleach=1.5.0=py35_0
- bokeh=0.12.4=py35_0
- boto=2.46.1=py35_0
- bottleneck=1.2.0=np112py35_0
- bz2file=0.98=py35_0
- cairo=1.14.8=0
- cffi=1.9.1=py35_0
- chardet=3.0.2=py35_0
- chest=0.2.3=py35_0
- click=6.7=py35_0
- cloudpickle=0.2.2=py35_0
- clyent=1.2.2=py35_0
- colorama=0.3.7=py35_0
- conda-forge::jupyter_contrib_core=0.3.0=py35_0
- conda-forge::jupyter_contrib_nbextensions=0.2.2=py35_0
- conda-forge::jupyter_nbextensions_configurator=0.2.3=py35_0
- configobj=5.0.6=py35_0
- contextlib2=0.5.4=py35_0
- cryptography=1.7.1=py35_0
- curl=7.52.1=0
- cycler=0.10.0=py35_0
- cymem=1.31.2=py35_0
- cython=0.25.2=py35_0
- cytoolz=0.8.2=py35_0
- dask=0.14.1=py35_0
- datashape=0.5.4=py35_0
- dbus=1.10.10=0
- decorator=4.0.11=py35_0
- dill=0.2.6=py35_0
- docutils=0.13.1=py35_0
- dynd-python=0.7.2=py35_0
- entrypoints=0.2.2=py35_1
- et_xmlfile=1.0.1=py35_0
- expat=2.1.0=0
- fastcache=1.0.2=py35_1
- filelock=2.0.7=py35_0
- flask=0.12.1=py35_0
- flask-cors=3.0.2=py35_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- gensim=1.0.1=np112py35_0
- get_terminal_size=1.0.0=py35_0
- gevent=1.2.1=py35_0
- glemaitre::imbalanced-learn=0.1.9=py35_0
- glib=2.50.2=1
- greenlet=0.4.12=py35_0
- gst-plugins-base
- gstreamer=1.8.0=0
- h5py=2.7.0=np112py35_0
- harfbuzz=0.9.39=2
- hdf5=1.8.17=1
- heapdict=1.0.0=py35_1
- html5lib=0.999=py35_0
- icu=54.1=0
- idna=2.2=py35_0
- imagesize=0.7.1=py35_0
- ipykernel=4.6.1=py35_0
- ipython=6.0.0=py35_0
- ipython_genutils=0.2.0=py35_0
- ipywidgets=6.0.0=py35_0
- isort=4.2.5=py35_0
- itsdangerous=0.24=py35_0
- jbig=2.1=0
- jdcal=1.3=py35_0
- jedi=0.9.0=py35_1
- jinja2=2.9.6=py35_0
- jpeg=9b=0
- jsonschema=2.6.0=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=5.0.1=py35_0
- jupyter_console=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- lazy-object-proxy=1.2.2=py35_0
- libdynd=0.7.2=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- llvmlite=0.17.0=py35_0
- locket=0.2.0=py35_1
- lxml=3.7.3=py35_0
- markupsafe=0.23=py35_2
- matplotlib=2.0.0=np112py35_0
- mistune=0.7.4=py35_0
- mkl=2017.0.1=0
- mkl-service=1.1.2=py35_3
- mlgill::textstat=0.3.1=py35_0
- mpmath=0.19=py35_1
- multipledispatch=0.4.9=py35_0
- murmurhash=0.26.4=py35_0
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=5.1.1=py35_0
- nbformat=4.3.0=py35_0
- nbpresent=3.0.2=py35_0
- networkx=1.11=py35_0
- nltk=3.2.2=py35_0
- nose=1.3.7=py35_1
- notebook=5.0.0=py35_0
- numba=0.32.0=np112py35_0
- numexpr=2.6.2=np112py35_0
- numpy=1.12.1=py35_0
- numpydoc=0.6.0=py35_0
- odo=0.5.0=py35_1
- olefile=0.44=py35_0
- openpyxl=2.4.1=py35_0
- openssl=1.0.2k=1
- pandas=0.19.2=np112py35_1
- pandocfilters=1.4.1=py35_0
- partd=0.3.7=py35_0
- patchelf=0.9=0
- path.py=10.3.1=py35_0
- pathlib2=2.2.1=py35_0
- patsy=0.4.1=py35_0
- paulgc::pyprind=2.9.8=py35_0
- pcre=8.39=1
- pep8=1.7.0=py35_0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=4.1.0=py35_0
- pip=9.0.1=py35_1
- pixman=0.34.0=0
- pkginfo=1.4.1=py35_0
- plac=0.9.6=py35_0
- ply=3.10=py35_0
- preshed=0.46.4=py35_0
- prompt_toolkit=1.0.14=py35_0
- psutil=5.2.2=py35_0
- ptyprocess=0.5.1=py35_0
- py=1.4.33=py35_0
- pyasn1=0.2.3=py35_0
- pycosat=0.6.2=py35_0
- pycparser=2.17=py35_0
- pycrypto=2.6.1=py35_4
- pycurl=7.43.0=py35_2
- pyflakes=1.5.0=py35_0
- pygments=2.2.0=py35_0
- pylint=1.6.4=py35_1
- pyopenssl=16.2.0=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_2
- pytables=3.3.0=np112py35_0
- pytest=3.0.7=py35_0
- python=3.5.3=1
- python-dateutil=2.6.0=py35_0
- pytz=2017.2=py35_0
- pywavelets=0.5.2=np112py35_0
- pyyaml=3.12=py35_0
- pyzmq=16.0.2=py35_0
- qt=5.6.2=3
- qtawesome=0.4.4=py35_0
- qtconsole=4.3.0=py35_0
- qtpy=1.2.1=py35_0
- readline=6.2=2
- redis=3.2.0=0
- redis-py=2.10.5=py35_0
- requests=2.13.0=py35_0
- rope=0.9.4=py35_1
- ruamel_yaml=0.11.14=py35_1
- scikit-image=0.13.0=np112py35_0
- scikit-learn=0.18.1=np112py35_1
- scipy=0.19.0=np112py35_0
- seaborn=0.7.1=py35_0
- semver=2.7.6=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- singledispatch=3.4.0.3=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- smart_open=1.5.2=py35_0
- snowballstemmer=1.2.1=py35_0
- sockjs-tornado=1.0.3=py35_0
- spacy=0.101.0=py35_0
- sphinx=1.5.4=py35_0
- sputnik=0.9.3=py35_1
- spyder=3.1.3=py35_0
- sqlalchemy=1.1.9=py35_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=np112py35_0
- sympy=1.0=py35_0
- terminado=0.6=py35_0
- testpath=0.3=py35_0
- thinc=5.0.8=py35_0
- tk=8.5.18=0
- toolz=0.8.2=py35_0
- tornado=4.5.1=py35_0
- traitlets=4.3.2=py35_0
- ujson=1.35=py35_0
- unicodecsv=0.14.1=py35_0
- wcwidth=0.1.7=py35_0
- werkzeug=0.12.1=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=2.0.0=py35_0
- wrapt=1.10.10=py35_0
- xlrd=1.0.0=py35_0
- xlsxwriter=0.9.6=py35_0
- xlwt=1.2.0=py35_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - dynd==0.7.3.dev1
  - et-xmlfile==1.0.1
  - fbprophet==0.1.post1
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-contrib-core==0.3.0
  - jupyter-contrib-nbextensions==0.2.2
  - jupyter-core==4.3.0
  - jupyter-nbextensions-configurator==0.2.3
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.14
  - pysentiment==0.1.2.1
  - pystan==2.14.0.0
  - rope-py3k==0.9.4.post1
  - smart-open==1.5.2
  - tables==3.3.0
  - xgboost==0.6a2
#prefix: #/home/jim/anaconda2/envs/py35
#prefix: /Users/eli/anaconda3/bin/python
